/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.closet.view;

import com.closet.config.DBConfig;
import com.closet.model.ImageBean;
import com.closet.model.UserBean;
import com.closet.util.ApplicationConfig;
import com.closet.util.FileUtil;
import com.closet.util.gui.GUITools;
import com.closet.util.gui.MyDialog;
import com.closet.util.gui.WrapLayout;
import java.awt.FlowLayout;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MakeVideoPanel extends javax.swing.JPanel {
    
    private static final String ALLSTYLE = "allStyle";
    private static final String ALLSEASON = "allSeason";
    private static final String ALLTYPE = "allType";
    private static final String ALLSITUATION = "allSituation";
    
    String style = ALLSTYLE;
    String season = ALLSEASON;
    String type = ALLTYPE;
    String situation = ALLSITUATION;
    
    String videoStyle = ALLSTYLE;
    String videoSeason = ALLSEASON;
    String videoType = ALLTYPE;
    String videoSituation = ALLSITUATION;
    ArrayList<ImageBean> allUserImage = new ArrayList<ImageBean>();
    ArrayList<ImageBean> selectImages = new ArrayList<ImageBean>();

    /**
     * Creates new form MakeVideoPanel
     * @param user
     */
    public MakeVideoPanel(UserBean user) {
        initComponents();
        imagesPanel.setLayout(new WrapLayout(FlowLayout.LEFT));
        addRadioToGroup();
        allUserImage = user.getUserAllImage();
        setUserImageDisplay(allUserImage);
    }

    private void addRadioToGroup(){
        styleButtonGroup.add(allStyle);
        styleButtonGroup.add(relaxation);
        styleButtonGroup.add(gentry);
        styleButtonGroup.add(business);
        styleButtonGroup.add(fashion);
        seasonButtonGroup.add(allSeason);
        seasonButtonGroup.add(spring);
        seasonButtonGroup.add(summer);
        seasonButtonGroup.add(autumn);
        seasonButtonGroup.add(winter);
        typeButtonGroup.add(allType);
        typeButtonGroup.add(blouse);
        typeButtonGroup.add(trousers);
        typeButtonGroup.add(coat);
    }
    
    private void stateChanged() {
        ArrayList<ImageBean> list = new ArrayList<ImageBean>();
        for(ImageBean image : allUserImage){
            if((style.equals(ALLSTYLE) || image.style.equalsIgnoreCase(style))  &&   
               (season.equals(ALLSEASON) || image.season.equalsIgnoreCase(season))  &&
               (type.equals(ALLTYPE) || image.type.equalsIgnoreCase(type)) ){
                list.add(image);
            }
        }
        setUserImageDisplay(list);
    }
    
    public void setUserImageDisplay(List<ImageBean> imageList){
        clear();
        for(final ImageBean im : imageList){
            final Image image = im.getPreviewImage(150);
            if(image != null){
                SelectImagePanel selectPanel = new SelectImagePanel(image) {
                    @Override
                    public void selectChanged(boolean isSelect) {
                        if(isSelect){
                            selectImages.add(im);
                        }else{
                            if(selectImages.contains(im)) selectImages.remove(im);
                        }
                    }
                };
                imagesPanel.add(selectPanel);
            }
        }
        imagesPanel.validate();
        imagesPanel.repaint();
        
    }
    
    private void clear(){
        imagesPanel.removeAll();
        selectImages.clear();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        styleButtonGroup = new javax.swing.ButtonGroup();
        seasonButtonGroup = new javax.swing.ButtonGroup();
        typeButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        allStyle = new javax.swing.JRadioButton();
        relaxation = new javax.swing.JRadioButton();
        gentry = new javax.swing.JRadioButton();
        business = new javax.swing.JRadioButton();
        fashion = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        allSeason = new javax.swing.JRadioButton();
        spring = new javax.swing.JRadioButton();
        summer = new javax.swing.JRadioButton();
        autumn = new javax.swing.JRadioButton();
        winter = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        allType = new javax.swing.JRadioButton();
        blouse = new javax.swing.JRadioButton();
        trousers = new javax.swing.JRadioButton();
        coat = new javax.swing.JRadioButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        allType2 = new javax.swing.JRadioButton();
        blouse2 = new javax.swing.JRadioButton();
        trousers2 = new javax.swing.JRadioButton();
        coat2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imagesPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        allStyle1 = new javax.swing.JRadioButton();
        relaxation1 = new javax.swing.JRadioButton();
        gentry1 = new javax.swing.JRadioButton();
        business1 = new javax.swing.JRadioButton();
        fashion1 = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        allSeason1 = new javax.swing.JRadioButton();
        spring1 = new javax.swing.JRadioButton();
        summer1 = new javax.swing.JRadioButton();
        autumn1 = new javax.swing.JRadioButton();
        winter1 = new javax.swing.JRadioButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        allType1 = new javax.swing.JRadioButton();
        blouse1 = new javax.swing.JRadioButton();
        trousers1 = new javax.swing.JRadioButton();
        coat1 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("请选择衣服类型：");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("款式：");
        jPanel5.add(jLabel2);

        allStyle.setSelected(true);
        allStyle.setText("全部");
        allStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStyleActionPerformed(evt);
            }
        });
        jPanel5.add(allStyle);

        relaxation.setText("休闲    ");
        relaxation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relaxationActionPerformed(evt);
            }
        });
        jPanel5.add(relaxation);

        gentry.setText("绅士  ");
        gentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gentryActionPerformed(evt);
            }
        });
        jPanel5.add(gentry);

        business.setText("商务");
        business.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessActionPerformed(evt);
            }
        });
        jPanel5.add(business);

        fashion.setText("时尚");
        fashion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fashionActionPerformed(evt);
            }
        });
        jPanel5.add(fashion);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("季节：");
        jPanel6.add(jLabel3);

        allSeason.setSelected(true);
        allSeason.setText("全部");
        allSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSeasonActionPerformed(evt);
            }
        });
        jPanel6.add(allSeason);

        spring.setText("春      ");
        spring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                springActionPerformed(evt);
            }
        });
        jPanel6.add(spring);

        summer.setText("夏    ");
        summer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summerActionPerformed(evt);
            }
        });
        jPanel6.add(summer);

        autumn.setText("秋  ");
        autumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autumnActionPerformed(evt);
            }
        });
        jPanel6.add(autumn);

        winter.setText("冬  ");
        winter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winterActionPerformed(evt);
            }
        });
        jPanel6.add(winter);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("类型：");
        jPanel7.add(jLabel4);

        allType.setSelected(true);
        allType.setText("全部");
        allType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTypeActionPerformed(evt);
            }
        });
        jPanel7.add(allType);

        blouse.setText("衬衣    ");
        blouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blouseActionPerformed(evt);
            }
        });
        jPanel7.add(blouse);

        trousers.setText("裤子  ");
        trousers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trousersActionPerformed(evt);
            }
        });
        jPanel7.add(trousers);

        coat.setText("外套");
        coat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coatActionPerformed(evt);
            }
        });
        jPanel7.add(coat);

        jPanel1.add(jPanel7);

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel10.setText("场合：");
        jPanel16.add(jLabel10);

        allType2.setSelected(true);
        allType2.setText("全部");
        allType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allType2ActionPerformed(evt);
            }
        });
        jPanel16.add(allType2);

        blouse2.setText("公共场合");
        blouse2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blouse2ActionPerformed(evt);
            }
        });
        jPanel16.add(blouse2);

        trousers2.setText("办公室");
        trousers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trousers2ActionPerformed(evt);
            }
        });
        jPanel16.add(trousers2);

        coat2.setText("就会");
        coat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coat2ActionPerformed(evt);
            }
        });
        jPanel16.add(coat2);

        jPanel1.add(jPanel16);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel5.setText("请选择要推荐的衣服：");
        jPanel2.add(jLabel5, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        imagesPanel.setPreferredSize(new java.awt.Dimension(500, 150));

        javax.swing.GroupLayout imagesPanelLayout = new javax.swing.GroupLayout(imagesPanel);
        imagesPanel.setLayout(imagesPanelLayout);
        imagesPanelLayout.setHorizontalGroup(
            imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        imagesPanelLayout.setVerticalGroup(
            imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(imagesPanel);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton2.setText("将所选文件导出到....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);

        jPanel2.add(jPanel9, java.awt.BorderLayout.SOUTH);

        add(jPanel2);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("请选择视频的属性：");
        jPanel12.add(jLabel6);

        jPanel10.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("款式：");
        jPanel13.add(jLabel7);

        allStyle1.setSelected(true);
        allStyle1.setText("全部");
        allStyle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStyle1ActionPerformed(evt);
            }
        });
        jPanel13.add(allStyle1);

        relaxation1.setText("休闲");
        relaxation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relaxation1ActionPerformed(evt);
            }
        });
        jPanel13.add(relaxation1);

        gentry1.setText("绅士");
        gentry1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gentry1ActionPerformed(evt);
            }
        });
        jPanel13.add(gentry1);

        business1.setText("商务");
        business1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                business1ActionPerformed(evt);
            }
        });
        jPanel13.add(business1);

        fashion1.setText("时尚");
        fashion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fashion1ActionPerformed(evt);
            }
        });
        jPanel13.add(fashion1);

        jPanel10.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel8.setText("季节：");
        jPanel14.add(jLabel8);

        allSeason1.setSelected(true);
        allSeason1.setText("全部");
        allSeason1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSeason1ActionPerformed(evt);
            }
        });
        jPanel14.add(allSeason1);

        spring1.setText("春  ");
        spring1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spring1ActionPerformed(evt);
            }
        });
        jPanel14.add(spring1);

        summer1.setText("夏  ");
        summer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summer1ActionPerformed(evt);
            }
        });
        jPanel14.add(summer1);

        autumn1.setText("秋  ");
        autumn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autumn1ActionPerformed(evt);
            }
        });
        jPanel14.add(autumn1);

        winter1.setText("冬  ");
        winter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winter1ActionPerformed(evt);
            }
        });
        jPanel14.add(winter1);

        jPanel10.add(jPanel14);

        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel9.setText("类型：");
        jPanel15.add(jLabel9);

        allType1.setSelected(true);
        allType1.setText("全部");
        allType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allType1ActionPerformed(evt);
            }
        });
        jPanel15.add(allType1);

        blouse1.setText("衬衣");
        blouse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blouse1ActionPerformed(evt);
            }
        });
        jPanel15.add(blouse1);

        trousers1.setText("裤子");
        trousers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trousers1ActionPerformed(evt);
            }
        });
        jPanel15.add(trousers1);

        coat1.setText("外套");
        coat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coat1ActionPerformed(evt);
            }
        });
        jPanel15.add(coat1);

        jPanel10.add(jPanel15);

        jPanel8.add(jPanel10);

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton3.setText("上传视频");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton3);

        jPanel8.add(jPanel11);

        add(jPanel8);

        jButton1.setText("完成");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void allStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStyleActionPerformed
        if(allStyle.isSelected()){
            style = ALLSTYLE;
            stateChanged();
        }
    }//GEN-LAST:event_allStyleActionPerformed

    private void relaxationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relaxationActionPerformed
        if(relaxation.isSelected()){
            style = "LEISURE";
            stateChanged();
        }
    }//GEN-LAST:event_relaxationActionPerformed

    private void gentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentryActionPerformed
        if(gentry.isSelected()){
            style = "GENTLEMAN";
            stateChanged();
        }
    }//GEN-LAST:event_gentryActionPerformed

    private void businessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessActionPerformed
        if(business.isSelected()){
            style = "BUSINESS";
            stateChanged();
        }
    }//GEN-LAST:event_businessActionPerformed

    private void fashionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fashionActionPerformed
        if(fashion.isSelected()){
            style = "FASHION";
            stateChanged();
        }
    }//GEN-LAST:event_fashionActionPerformed

    private void allSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSeasonActionPerformed
        if(allSeason.isSelected()){
            season = ALLSEASON;
            stateChanged();
        }
    }//GEN-LAST:event_allSeasonActionPerformed

    private void springActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_springActionPerformed
        if(spring.isSelected()){
            season = "SPRING";
            stateChanged();
        }
    }//GEN-LAST:event_springActionPerformed

    private void summerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summerActionPerformed
        if(summer.isSelected()){
            season = "SUMMER";
            stateChanged();
        }
    }//GEN-LAST:event_summerActionPerformed

    private void autumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autumnActionPerformed
        if(autumn.isSelected()){
            season = "AUTUMN";
            stateChanged();
        }
    }//GEN-LAST:event_autumnActionPerformed

    private void winterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winterActionPerformed
        if(winter.isSelected()){
            season = "WINTER";
            stateChanged();
        }
    }//GEN-LAST:event_winterActionPerformed

    private void allTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTypeActionPerformed
        if(allType.isSelected()){
            type = ALLTYPE;
            stateChanged();
        }
    }//GEN-LAST:event_allTypeActionPerformed

    private void blouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blouseActionPerformed
        if(blouse.isSelected()){
            type = "SLEEVED";
            stateChanged();
        }
    }//GEN-LAST:event_blouseActionPerformed

    private void trousersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trousersActionPerformed
        if(trousers.isSelected()){
            type = "TROUSERS";
            stateChanged();
        }
    }//GEN-LAST:event_trousersActionPerformed

    private void coatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coatActionPerformed
        if(coat.isSelected()){
            type = "OVERCOAT";
            stateChanged();
        }
    }//GEN-LAST:event_coatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(selectImages.size() <= 0){
            JOptionPane.showMessageDialog(this, "未选择任何图片", "提示", JOptionPane.WARNING_MESSAGE);
            return;
        }
        File savePath = new File(ApplicationConfig.getConfig("save.path", "D:\\"));
        JFileChooser fileChooser = new JFileChooser(savePath);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        while (true) {
            int rVal = fileChooser.showSaveDialog(this);                 //类指当前你编写的类名
            if (rVal == JFileChooser.APPROVE_OPTION) {
                if (fileChooser.getSelectedFile().getParent().equals("::{20D04FE0-3AEA-1069-A2D8-08002B30309D}")) {
                    JOptionPane.showMessageDialog(this, "无法保存到此处，请选择其他位置", "另存为", JOptionPane.WARNING_MESSAGE);
                }else{
                    ApplicationConfig.saveConfig("save.path", fileChooser.getSelectedFile().getPath());
                    savePath = fileChooser.getSelectedFile();
                    break;
                }
            } else {
                savePath = null;
                break;
            }
        }
        
        if(savePath != null){
            for(ImageBean image : selectImages){
                File saveFile = new File(savePath, image.fileName);
                if(saveFile.exists()){
                    int res = JOptionPane.showConfirmDialog(this, "该目录下的"+image.imageName+"文件已存在\n是否覆盖？", "文件重名", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if(res == JOptionPane.NO_OPTION ){
                        continue;
                    }
                }
                FileUtil.copy((new File(DBConfig.imageLocation+"/"+image.fileName)), saveFile);
            }
            new MyDialog(null, "导出成功");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void allStyle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStyle1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allStyle1ActionPerformed

    private void relaxation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relaxation1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relaxation1ActionPerformed

    private void gentry1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentry1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gentry1ActionPerformed

    private void business1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_business1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_business1ActionPerformed

    private void fashion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fashion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fashion1ActionPerformed

    private void allSeason1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSeason1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allSeason1ActionPerformed

    private void spring1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spring1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spring1ActionPerformed

    private void summer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_summer1ActionPerformed

    private void autumn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autumn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_autumn1ActionPerformed

    private void winter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_winter1ActionPerformed

    private void allType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allType1ActionPerformed

    private void blouse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blouse1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blouse1ActionPerformed

    private void trousers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trousers1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trousers1ActionPerformed

    private void coat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coat1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       GUITools.disposeDialog(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void allType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allType2ActionPerformed

    private void blouse2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blouse2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blouse2ActionPerformed

    private void trousers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trousers2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trousers2ActionPerformed

    private void coat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coat2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allSeason;
    private javax.swing.JRadioButton allSeason1;
    private javax.swing.JRadioButton allStyle;
    private javax.swing.JRadioButton allStyle1;
    private javax.swing.JRadioButton allType;
    private javax.swing.JRadioButton allType1;
    private javax.swing.JRadioButton allType2;
    private javax.swing.JRadioButton autumn;
    private javax.swing.JRadioButton autumn1;
    private javax.swing.JRadioButton blouse;
    private javax.swing.JRadioButton blouse1;
    private javax.swing.JRadioButton blouse2;
    private javax.swing.JRadioButton business;
    private javax.swing.JRadioButton business1;
    private javax.swing.JRadioButton coat;
    private javax.swing.JRadioButton coat1;
    private javax.swing.JRadioButton coat2;
    private javax.swing.JRadioButton fashion;
    private javax.swing.JRadioButton fashion1;
    private javax.swing.JRadioButton gentry;
    private javax.swing.JRadioButton gentry1;
    private javax.swing.JPanel imagesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton relaxation;
    private javax.swing.JRadioButton relaxation1;
    private javax.swing.ButtonGroup seasonButtonGroup;
    private javax.swing.JRadioButton spring;
    private javax.swing.JRadioButton spring1;
    private javax.swing.ButtonGroup styleButtonGroup;
    private javax.swing.JRadioButton summer;
    private javax.swing.JRadioButton summer1;
    private javax.swing.JRadioButton trousers;
    private javax.swing.JRadioButton trousers1;
    private javax.swing.JRadioButton trousers2;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JRadioButton winter;
    private javax.swing.JRadioButton winter1;
    // End of variables declaration//GEN-END:variables
}
