/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.closet.view;

import com.closet.config.DBConfig;
import com.closet.model.ImageBean;
import com.closet.model.UserBean;
import com.closet.util.gui.WrapLayout;
import java.awt.FlowLayout;
import java.awt.Image;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class MakeVideoPanel extends javax.swing.JPanel {
    
    private static final String ALLSTYLE = "allStyle";
    private static final String ALLSEASON = "allSeason";
    private static final String ALLTYPE = "allType";
    
    String style = ALLSTYLE;
    String season = ALLSEASON;
    String type = ALLTYPE;
    ArrayList<ImageBean> allUserImage = new ArrayList<ImageBean>();
    ArrayList<ImageBean> selectImages = new ArrayList<ImageBean>();

    /**
     * Creates new form MakeVideoPanel
     * @param user
     */
    public MakeVideoPanel(UserBean user) {
        initComponents();
        imagesPanel.setLayout(new WrapLayout(FlowLayout.LEFT));
        addRadioToGroup();
        allUserImage = user.getUserAllImage();
        setUserImageDisplay(allUserImage);
    }

    private void addRadioToGroup(){
        styleButtonGroup.add(allStyle);
        styleButtonGroup.add(relaxation);
        styleButtonGroup.add(gentry);
        styleButtonGroup.add(business);
        styleButtonGroup.add(fashion);
        seasonButtonGroup.add(allSeason);
        seasonButtonGroup.add(spring);
        seasonButtonGroup.add(summer);
        seasonButtonGroup.add(autumn);
        seasonButtonGroup.add(winter);
        typeButtonGroup.add(allType);
        typeButtonGroup.add(blouse);
        typeButtonGroup.add(trousers);
        typeButtonGroup.add(coat);
    }
    
    private void stateChanged() {
        ArrayList<ImageBean> list = new ArrayList<ImageBean>();
        for(ImageBean image : allUserImage){
            if((style.equals(ALLSTYLE) || image.style.equalsIgnoreCase(style))  &&   
               (season.equals(ALLSEASON) || image.season.equalsIgnoreCase(season))  &&
               (type.equals(ALLTYPE) || image.type.equalsIgnoreCase(type)) ){
                list.add(image);
            }
        }
        setUserImageDisplay(list);
    }
    
    public void setUserImageDisplay(List<ImageBean> imageList){
        clear();
        for(final ImageBean im : imageList){
            final Image image = im.getPreviewImage(150);
            if(image != null){
                SelectImagePanel selectPanel = new SelectImagePanel(image) {
                    @Override
                    public void selectChanged(boolean isSelect) {
                        if(isSelect){
                            selectImages.add(im);
                        }
                    }
                };
                imagesPanel.add(selectPanel);
            }
        }
        imagesPanel.validate();
        imagesPanel.repaint();
        
    }
    
    private void clear(){
        imagesPanel.removeAll();
        selectImages.clear();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        styleButtonGroup = new javax.swing.ButtonGroup();
        seasonButtonGroup = new javax.swing.ButtonGroup();
        typeButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        allStyle = new javax.swing.JRadioButton();
        relaxation = new javax.swing.JRadioButton();
        gentry = new javax.swing.JRadioButton();
        business = new javax.swing.JRadioButton();
        fashion = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        allSeason = new javax.swing.JRadioButton();
        spring = new javax.swing.JRadioButton();
        summer = new javax.swing.JRadioButton();
        autumn = new javax.swing.JRadioButton();
        winter = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        allType = new javax.swing.JRadioButton();
        blouse = new javax.swing.JRadioButton();
        trousers = new javax.swing.JRadioButton();
        coat = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        imagesPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("请选择衣服类型：");
        jPanel4.add(jLabel1);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("款式：");
        jPanel5.add(jLabel2);

        allStyle.setSelected(true);
        allStyle.setText("全部");
        allStyle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allStyleActionPerformed(evt);
            }
        });
        jPanel5.add(allStyle);

        relaxation.setText("休闲");
        relaxation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relaxationActionPerformed(evt);
            }
        });
        jPanel5.add(relaxation);

        gentry.setText("绅士");
        gentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gentryActionPerformed(evt);
            }
        });
        jPanel5.add(gentry);

        business.setText("商务");
        business.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessActionPerformed(evt);
            }
        });
        jPanel5.add(business);

        fashion.setText("时尚");
        fashion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fashionActionPerformed(evt);
            }
        });
        jPanel5.add(fashion);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("季节：");
        jPanel6.add(jLabel3);

        allSeason.setSelected(true);
        allSeason.setText("全部");
        allSeason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allSeasonActionPerformed(evt);
            }
        });
        jPanel6.add(allSeason);

        spring.setText("春  ");
        spring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                springActionPerformed(evt);
            }
        });
        jPanel6.add(spring);

        summer.setText("夏  ");
        summer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summerActionPerformed(evt);
            }
        });
        jPanel6.add(summer);

        autumn.setText("秋  ");
        autumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autumnActionPerformed(evt);
            }
        });
        jPanel6.add(autumn);

        winter.setText("冬  ");
        winter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winterActionPerformed(evt);
            }
        });
        jPanel6.add(winter);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("类型：");
        jPanel7.add(jLabel4);

        allType.setSelected(true);
        allType.setText("全部");
        allType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allTypeActionPerformed(evt);
            }
        });
        jPanel7.add(allType);

        blouse.setText("衬衣");
        blouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blouseActionPerformed(evt);
            }
        });
        jPanel7.add(blouse);

        trousers.setText("裤子");
        trousers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trousersActionPerformed(evt);
            }
        });
        jPanel7.add(trousers);

        coat.setText("外套");
        coat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coatActionPerformed(evt);
            }
        });
        jPanel7.add(coat);

        jPanel1.add(jPanel7);

        add(jPanel1);

        jPanel2.setPreferredSize(null);
        jPanel2.setLayout(new java.awt.BorderLayout(5, 0));

        jLabel5.setText("请选择要推荐的衣服：");
        jPanel2.add(jLabel5, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(null);

        imagesPanel.setPreferredSize(new java.awt.Dimension(500, 150));

        javax.swing.GroupLayout imagesPanelLayout = new javax.swing.GroupLayout(imagesPanel);
        imagesPanel.setLayout(imagesPanelLayout);
        imagesPanelLayout.setHorizontalGroup(
            imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        imagesPanelLayout.setVerticalGroup(
            imagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(imagesPanel);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(null);
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton2.setText("将所选文件导出到....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);

        jPanel2.add(jPanel9, java.awt.BorderLayout.SOUTH);

        add(jPanel2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        add(jPanel8);

        jButton1.setText("完成");
        jPanel3.add(jButton1);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void allStyleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allStyleActionPerformed
        if(allStyle.isSelected()){
            style = ALLSTYLE;
            stateChanged();
        }
    }//GEN-LAST:event_allStyleActionPerformed

    private void relaxationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relaxationActionPerformed
        if(relaxation.isSelected()){
            style = "LEISURE";
            stateChanged();
        }
    }//GEN-LAST:event_relaxationActionPerformed

    private void gentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gentryActionPerformed
        if(gentry.isSelected()){
            style = "GENTLEMAN";
            stateChanged();
        }
    }//GEN-LAST:event_gentryActionPerformed

    private void businessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessActionPerformed
        if(business.isSelected()){
            style = "BUSINESS";
            stateChanged();
        }
    }//GEN-LAST:event_businessActionPerformed

    private void fashionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fashionActionPerformed
        if(fashion.isSelected()){
            style = "FASHION";
            stateChanged();
        }
    }//GEN-LAST:event_fashionActionPerformed

    private void allSeasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allSeasonActionPerformed
        if(allSeason.isSelected()){
            season = ALLSEASON;
            stateChanged();
        }
    }//GEN-LAST:event_allSeasonActionPerformed

    private void springActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_springActionPerformed
        if(spring.isSelected()){
            season = "SPRING";
            stateChanged();
        }
    }//GEN-LAST:event_springActionPerformed

    private void summerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summerActionPerformed
        if(summer.isSelected()){
            season = "SUMMER";
            stateChanged();
        }
    }//GEN-LAST:event_summerActionPerformed

    private void autumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autumnActionPerformed
        if(autumn.isSelected()){
            season = "AUTUMN";
            stateChanged();
        }
    }//GEN-LAST:event_autumnActionPerformed

    private void winterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winterActionPerformed
        if(winter.isSelected()){
            season = "WINTER";
            stateChanged();
        }
    }//GEN-LAST:event_winterActionPerformed

    private void allTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allTypeActionPerformed
        if(allType.isSelected()){
            type = ALLTYPE;
            stateChanged();
        }
    }//GEN-LAST:event_allTypeActionPerformed

    private void blouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blouseActionPerformed
        if(blouse.isSelected()){
            type = "SLEEVED";
            stateChanged();
        }
    }//GEN-LAST:event_blouseActionPerformed

    private void trousersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trousersActionPerformed
        if(trousers.isSelected()){
            type = "TROUSERS";
            stateChanged();
        }
    }//GEN-LAST:event_trousersActionPerformed

    private void coatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coatActionPerformed
        if(coat.isSelected()){
            type = "OVERCOAT";
            stateChanged();
        }
    }//GEN-LAST:event_coatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(selectImages.size() <= 0){
            JOptionPane.showMessageDialog(this, "未选择任何图片", "提示", JOptionPane.WARNING_MESSAGE);
            return;
        }
        File savePath = new File(System.getProperty("save.path", "D:\\"));
        JFileChooser fileChooser = new JFileChooser(savePath);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        while (true) {
            int rVal = fileChooser.showSaveDialog(this);                 //类指当前你编写的类名
            if (rVal == JFileChooser.APPROVE_OPTION) {
                if (fileChooser.getSelectedFile().getParent().equals("::{20D04FE0-3AEA-1069-A2D8-08002B30309D}")) {
                    JOptionPane.showMessageDialog(this, "无法保存到此处，请选择其他位置", "另存为", JOptionPane.WARNING_MESSAGE);
                }else{
                    System.setProperty("save.path", fileChooser.getSelectedFile().getPath());
                    savePath = fileChooser.getSelectedFile();
                    break;
                }
            } else {
                savePath = null;
                break;
            }
        }
        
        if(savePath != null){
            for(ImageBean image : selectImages){
                File saveFile = new File(savePath, image.fileName);
                if(saveFile.exists()){
                    int res = JOptionPane.showConfirmDialog(this, "该目录下的"+image.imageName+"文件已存在\n是否覆盖？", "文件重名", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if(res == JOptionPane.NO_OPTION ){
                        continue;
                    }
                }
                copy((new File(DBConfig.imageLocation+"/"+image.fileName)), saveFile);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void copy(File source, File dest){
        FileInputStream fin = null;
        try {
            System.out.println("source>>>>"+source);
            fin = new FileInputStream(source);
            BufferedInputStream in = new BufferedInputStream(fin);
            FileOutputStream fout = new FileOutputStream(dest);
            BufferedOutputStream out = new BufferedOutputStream(fout);
            int a;
            while ((a = in.read()) != -1) {
                out.write(a);
            }   out.flush();
            out.flush();
            fout.flush();
            fout.close();
            fin.close();
        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allSeason;
    private javax.swing.JRadioButton allStyle;
    private javax.swing.JRadioButton allType;
    private javax.swing.JRadioButton autumn;
    private javax.swing.JRadioButton blouse;
    private javax.swing.JRadioButton business;
    private javax.swing.JRadioButton coat;
    private javax.swing.JRadioButton fashion;
    private javax.swing.JRadioButton gentry;
    private javax.swing.JPanel imagesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton relaxation;
    private javax.swing.ButtonGroup seasonButtonGroup;
    private javax.swing.JRadioButton spring;
    private javax.swing.ButtonGroup styleButtonGroup;
    private javax.swing.JRadioButton summer;
    private javax.swing.JRadioButton trousers;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JRadioButton winter;
    // End of variables declaration//GEN-END:variables
}
