/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.closet.view;

import com.closet.model.ImageBean;
import com.closet.model.UserBean;
import javax.swing.JScrollBar;

/**
 *
 * @author ºÚ¿Í
 */
public class MakeModePanel extends javax.swing.JPanel {

    /**
     * Creates new form MakeModePanel
     * @param user
     */
    public MakeModePanel(UserBean user) {
        initComponents();
        JScrollBar bar = jScrollPane1.getVerticalScrollBar();
        bar.setUnitIncrement(12);
        for(ImageBean image : user.getUserAllImage()){
            centerPanel.add(new ModePanelItem(image));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        centerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        centerPanel.setLayout(new javax.swing.BoxLayout(centerPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(centerPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
