/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.closet.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Administrator
 */
public abstract class SelectImagePanel extends javax.swing.JPanel {
    
    private boolean isSelect = false;
    JLabel selectLabel;
    Image image;

    /**
     * Creates new form SelectImagePanel
     */
    public SelectImagePanel(Image image) {
        initComponents();
        try {
            selectLabel = new JLabel(new ImageIcon(ImageIO.read(this.getClass().getResourceAsStream("/select.png"))));
        } catch (IOException ex) {
            selectLabel = null;
        }
        this.image = image;
        int imageWidth = image.getWidth(this);
        int imageHeight = image.getHeight(this);
        Dimension d = new Dimension(imageWidth, imageHeight);
        setPreferredSize(d);
        setMinimumSize(d);
        setMaximumSize(d);
    }
    
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }

    public abstract void selectChanged(boolean isSelect);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(isSelect){
            remove(selectLabel);
        }else{
            add(selectLabel, BorderLayout.CENTER);
        }
        isSelect = !isSelect;
        revalidate();
        repaint();
        selectChanged(isSelect);
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
