/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.closet.view;

import com.closet.model.ImageBean;
import com.closet.model.UserBean;
import com.closet.util.TransferUtil;
import com.closet.util.gui.GUITools;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Liumb
 */
public class UserItem extends javax.swing.JPanel {

    /**
     * Creates new form UserItem
     * @param user
     */
    UserBean user;
    String statusText = "<html><font color='red'>存在未建模对象</font></html>";
    
    public UserItem(UserBean user) {
        initComponents();
        this.user = user;
        this.userName.setText(user.userName);
        if(user.sex != null){
            this.sex.setText(user.sex.equalsIgnoreCase("M") ? "男" : "女");
        }else{
            this.sex.setText("");
        }
        this.age.setText(user.age+"岁");
        this.height.setText("身高："+TransferUtil.null2String(user.height));
        this.weight.setText("体重："+TransferUtil.null2String(user.weight));
        this.bust.setText("胸围："+TransferUtil.null2String(user.bust));
        this.waist.setText("腰围："+TransferUtil.null2String(user.waist));
        this.hip.setText("臀围："+TransferUtil.null2String(user.hip));
        for(ImageBean image : user.getUserAllImage()){
            setStauusVisible(image.afterDeal.isEmpty());
            previewPanel.add(addPreview(image));
        }
        
    }
    
    public void setStauusVisible(boolean visible){
        if(visible){
            status.setText(statusText);
        }else{
            status.setText("");
        }
    }

    public JPanel addPreview(ImageBean image){
        final Image im = image.getPreviewImage(75);
        if(im != null){
            JPanel panel = new JPanel(){
                @Override
                public void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    g.drawImage(im, 0, 0, this);
                }
            };
            int imageWidth = im.getWidth(this);
            int imageHeight = im.getHeight(this);
            System.out.println("imageWidth::"+imageWidth+"    imageHeight"+imageHeight);
            Dimension d = new Dimension(imageWidth, imageHeight);
            panel.setPreferredSize(d);
            panel.setMinimumSize(d);
            panel.setMaximumSize(d);
            return panel;
        }else{
            JPanel panel = new JPanel(new BorderLayout());
            JLabel label = new JLabel(image.fileName);
            panel.add(label, BorderLayout.CENTER);
            return panel;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        age = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        status = new javax.swing.JLabel();
        previewPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        height = new javax.swing.JLabel();
        weight = new javax.swing.JLabel();
        bust = new javax.swing.JLabel();
        waist = new javax.swing.JLabel();
        hip = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setMaximumSize(new java.awt.Dimension(2147483647, 140));
        setMinimumSize(new java.awt.Dimension(0, 140));
        setPreferredSize(new java.awt.Dimension(563, 140));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(70, 32767));
        jPanel2.setMinimumSize(new java.awt.Dimension(70, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(70, 30));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        userName.setFont(new java.awt.Font("黑体", 1, 18)); // NOI18N
        userName.setText("userName");
        jPanel7.add(userName);

        jLabel2.setText("  ");
        jPanel7.add(jLabel2);

        sex.setText("sex");
        sex.setPreferredSize(null);
        jPanel7.add(sex);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(2, 20));
        jPanel7.add(jSeparator1);

        age.setText("age");
        age.setPreferredSize(null);
        jPanel7.add(age);

        jPanel2.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));
        jPanel8.add(status);

        jPanel2.add(jPanel8);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        previewPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
        add(previewPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(563, 30));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(32767, 4));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 4));
        jPanel3.setPreferredSize(new java.awt.Dimension(243, 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        height.setText("height");
        jPanel4.add(height);

        weight.setText("weight");
        jPanel4.add(weight);

        bust.setText("bust");
        jPanel4.add(bust);

        waist.setText("waist");
        jPanel4.add(waist);

        hip.setText("hip");
        jPanel4.add(hip);

        jPanel6.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 0));

        jButton2.setText("服装建模");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton1.setText("虚拟试衣");
        jButton1.setPreferredSize(new java.awt.Dimension(81, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel6.add(jPanel5);

        jPanel1.add(jPanel6);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MakeVideoPanel makeVideo = new MakeVideoPanel(user);
        makeVideo.setName("上传视频");
        JDialog dialog = GUITools.showAsDialog(makeVideo, true);
        dialog.setSize(new Dimension(800, 560));
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(user.getUserAllImage().size() <= 0){
            JOptionPane.showMessageDialog(this, "该用户无需要建模的图片", "操作提示", JOptionPane.WARNING_MESSAGE);
            return;
        }
        MakeModePanel makeMode = new MakeModePanel(user);
        makeMode.setName("建模");
        JDialog dialog = GUITools.showAsDialog(makeMode, true);
        dialog.setSize(new Dimension(800, 600));
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel age;
    private javax.swing.JLabel bust;
    private javax.swing.JLabel height;
    private javax.swing.JLabel hip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JLabel sex;
    private javax.swing.JLabel status;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel waist;
    private javax.swing.JLabel weight;
    // End of variables declaration//GEN-END:variables
}
